import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * This sidebar is explicitly defined to match the modular structure of the textbook.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  textbookSidebar: [
    'index',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        {
          type: 'doc',
          id: 'modules/module-1-ros2/index',
          label: 'Module Introduction',
        },
        {
          type: 'doc',
          id: 'modules/module-1-ros2/chapters/chapter-ros2-core-concepts',
          label: 'ROS 2 Core Concepts',
        },
        {
          type: 'doc',
          id: 'modules/module-1-ros2/chapters/chapter-humanoid-urdf-modeling',
          label: 'Humanoid URDF Modeling',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        {
          type: 'doc',
          id: 'modules/module-2-digital-twin/index',
          label: 'Module Introduction',
        },
        {
          type: 'doc',
          id: 'modules/module-2-digital-twin/chapters/chapter-gazebo-digital-twins',
          label: 'Gazebo Digital Twins',
        },
        {
          type: 'doc',
          id: 'modules/module-2-digital-twin/chapters/chapter-unity-hri',
          label: 'Unity HRI',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI Robot Brain (NVIDIA Isaac)',
      items: [
        {
          type: 'doc',
          id: 'modules/module-3-nvidia-isaac/index',
          label: 'Module Introduction',
        },
        {
          type: 'doc',
          id: 'modules/module-3-nvidia-isaac/chapters/chapter-isaac-sim-synthetic-data',
          label: 'Isaac Sim & Synthetic Data',
        },
        {
          type: 'doc',
          id: 'modules/module-3-nvidia-isaac/chapters/chapter-isaac-ros-navigation-slam',
          label: 'Isaac ROS Navigation & SLAM',
        },
        {
          type: 'doc',
          id: 'modules/module-3-nvidia-isaac/chapters/chapter-bipedal-planning-isaac',
          label: 'Bipedal Planning with Isaac',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision–Language–Action (VLA)',
      items: [
        {
          type: 'doc',
          id: 'modules/module-4-vision-language-action/index',
          label: 'Module Introduction',
        },
        {
          type: 'doc',
          id: 'modules/module-4-vision-language-action/chapters/chapter-vla-systems',
          label: 'VLA Systems',
        },
        {
          type: 'doc',
          id: 'modules/module-4-vision-language-action/chapters/chapter-capstone-humanoid-pipeline',
          label: 'Capstone Humanoid Pipeline',
        },
      ],
    },
    {
      type: 'category',
      label: 'Hardware Architecture',
      items: [
        {
          type: 'doc',
          id: 'hardware-architecture/workstation-jetson-sensors',
          label: 'Hardware Architecture',
        },
      ],
    },
    // Modules will be added here as they are created
  ],
};

export default sidebars;
